print(4+3)
print(4-3)
print(4*3)
print(4%3)
print(4/3)
print(4**3)
print(4//3)


print('Angie')
print('Kate')
print('mexico')
print('im enjoying 30 days of python')
 
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type({'Angie', 'phyton','Mexico'}))
print(type('Angie'))
print(type('Kate'))
print(type('mexico'))